// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ConnectSSH(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteConnection(arg1:string):Promise<string>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<string>;

export function GetSavedConnections():Promise<Array<backend.SavedConnection>>;

export function SaveConnection(arg1:backend.SavedConnection):Promise<string>;
